spring.application.name=nail-salon-appointment-scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/nail_salon_db
spring.datasource.username=${USER}
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:seed.sql